export class InsurerQuotesDetails {
    enquiryId: string;
    quoteType: string = "quick";
    idv_up: string = "0";
    qid: string = "";
    type: string;
    reg_no: string;
    tppd_restricted_to: boolean;
    make: string;
    model: string;
    variant: string;
    fuel_type: string;
    cubic_capacity: string;
    imt23: boolean = false;
    tp_expire_policy_number?: any = null;
    tp_company?: any = null;
    tp_policy_expire_date?: any =null;
    pa_cover_year?: any = null;
    policy_types?: any = null;
    valid_license: boolean = true;
    already_policy: boolean = false;
    cover_for?: any = null;
    organization_name?: any = null;
    cover?: any = null;
    pa_coverbike: boolean = false;
    zero_deptss: boolean = false;
    engine_protector: boolean = false;
    consumables: boolean = false;
    road_side_assistance: boolean = false;
    return_invoice: boolean = false;
    ncb?: any = null;
    ncb_old?: any = null;
    claim: boolean;
    owner_change: boolean = false;
    zero_dept_prev_policy: boolean = false;
    manufacture_date: string = null;
    purchase_date: string = null;
    registration_date: string = null;
    policy_expire_date: string;
    policy_number: string = null;
    vehicle_owned_by: string = null;
    registration_no: string;
    manufacturer: string;
    year: string;
    previous: boolean;
    policy_type: string = null;
    previous_policy_type: string = null;
    own_damage: boolean = false;
    pa_cover: boolean = false;
    policy_expiry: string = null;
    puc: boolean = false;
    pincode: string;
    customer_mobile: string;
    customer_email: string;
}